package uz.pizzaking.entity.enums;

public enum States {
    LANGUAGE_SELECTION, PHONE_NUMBER_REQUEST, MAIN_MENU, MAIN_ADMIN,
    WAIT_MESSAGE, PRODUCT_MENU, PRODUCT_SUB_MENU, ORDER_CONFIRMATION, RESPONSE_TO_USER,
    SEND_MESSAGE_TO_ALL, SETTINGS
}
